[[language]]
name = "typescript"
injection-regex = "^(ts|typescript|js|javascript)$"
file-types = ["ts","js"]
auto-format = true
language-server = { command = "deno", args = ["lsp"] }
config = { deno = { enable = true, lint = true, unstable = true } }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "typescript"
source = { git = "https://github.com/tree-sitter/tree-sitter-typescript", rev = "3e897ea5925f037cfae2e551f8e6b12eec2a201a", subpath = "typescript" }

[[language]]
name = "nix"
file-types = ["nix"]
roots = ["flake.nix", "shell.nix", "default.nix", ".git"]
auto-format = true
language-server = { command = "rnix-lsp" }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "nix"
source = { git = "https://github.com/cstrahan/tree-sitter-nix", rev = "6b71a810c0acd49b980c50fc79092561f7cee307" }